version: '3.9'
services:
  db:
    image: postgres:15.5
    container_name: getcomunes-backend-database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - getcomunes-bridge
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: getcomunes-backend-app
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - getcomunes-bridge
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:1.24.0-alpine
    container_name: getcomunes-nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
    networks:
      - getcomunes-bridge
    depends_on:
      - app

volumes:
  db-data:

networks:
  getcomunes-bridge:
